### ISSUE TITLE
What about ESP32 and ESP32S3?

### ISSUE THREAD

**Issue by dglaude** [anecdata/Socket#1]
In your explanation you identify ESP32SPI (Nina FW?), ESP32S2, PicoW, Wiznet.
But what about ESP32S3 and the old (newly supported again) ESP32?
Are they in the same categorie has ESP32S2?

**Comment by anecdata** [comment]
Yes, ESP32SPI == Nina FW == Airlift

I've only posted what I've personally tested. I use ESP32-S2 predominantly since it's stable, has SSL, etc. Proving that out creates a baseline for other ESP32-variants. I don't necessarily plan to fully test the other variants... maybe the ESP32-S3 in time, when that part of the port is more stable. I don't have any plans to test ESP32 or ESP32-C3.

There is only one socket [API](https://docs.circuitpython.org/en/latest/shared-bindings/socketpool/index.html) for the `espressif` port. In theory, if it works on one ESP-variant, it _should_ work on another, and if it doesn't then an issue could be filed in the Adafruit `circuitpython` repo.

**Comment by anecdata** [comment]
I think this is answered. Closing. Feel free to re-open or open a new issue if questions remain.
